In [18]:
NDP_CUSTOMERS = 5
HDP_CUSTOMERS = 10
CARS = 2
FORCE_SAME_CAR = False


In [2]:
import numpy as np

np.random.seed(42)


ndp_customers_orders, hdp_customers_orders = [
    [np.random.permutation(customers) for _ in range(100)]
    for customers in [NDP_CUSTOMERS, HDP_CUSTOMERS]
]

ndp_customers_orders, hdp_customers_orders

([array([1, 4, 2, 0, 3]),
  array([3, 1, 2, 0, 4]),
  array([1, 0, 3, 4, 2]),
  array([0, 1, 2, 3, 4]),
  array([0, 2, 3, 1, 4]),
  array([4, 2, 0, 3, 1]),
  array([2, 0, 4, 1, 3]),
  array([1, 2, 4, 0, 3]),
  array([0, 3, 1, 4, 2]),
  array([0, 1, 2, 4, 3]),
  array([0, 1, 4, 3, 2]),
  array([1, 3, 4, 2, 0]),
  array([3, 1, 2, 0, 4]),
  array([4, 2, 1, 0, 3]),
  array([2, 3, 4, 0, 1]),
  array([0, 4, 2, 3, 1]),
  array([1, 4, 2, 0, 3]),
  array([4, 2, 1, 3, 0]),
  array([0, 2, 4, 1, 3]),
  array([2, 0, 4, 3, 1]),
  array([0, 2, 3, 4, 1]),
  array([0, 4, 2, 1, 3]),
  array([4, 2, 1, 0, 3]),
  array([2, 1, 0, 3, 4]),
  array([2, 0, 1, 3, 4]),
  array([1, 2, 0, 4, 3]),
  array([1, 3, 0, 2, 4]),
  array([3, 1, 4, 2, 0]),
  array([1, 4, 2, 3, 0]),
  array([1, 3, 4, 0, 2]),
  array([3, 1, 4, 2, 0]),
  array([4, 3, 2, 0, 1]),
  array([2, 4, 0, 1, 3]),
  array([3, 0, 1, 2, 4]),
  array([1, 3, 4, 0, 2]),
  array([4, 1, 3, 0, 2]),
  array([1, 3, 4, 0, 2]),
  array([3, 2, 0, 4, 1]),
  array([2, 

In [3]:
import numpy as np


def segment_customers_orders_by_cars(customers_orders, cars):
    customers_by_cars_solutions = [
        np.array_split(customers_order, cars) for customers_order in customers_orders
    ]
    customers_by_cars_solutions = [
        [list(car) for car in solution] for solution in customers_by_cars_solutions
    ]

    return customers_by_cars_solutions


# Simplified assignment of customer orders by cars
ndp_customers_by_cars, hdp_customers_by_cars = [
    segment_customers_orders_by_cars(customers_orders=orders, cars=CARS)
    for orders in (ndp_customers_orders, hdp_customers_orders)
]
ndp_customers_by_cars

[[[1, 4, 2], [0, 3]],
 [[3, 1, 2], [0, 4]],
 [[1, 0, 3], [4, 2]],
 [[0, 1, 2], [3, 4]],
 [[0, 2, 3], [1, 4]],
 [[4, 2, 0], [3, 1]],
 [[2, 0, 4], [1, 3]],
 [[1, 2, 4], [0, 3]],
 [[0, 3, 1], [4, 2]],
 [[0, 1, 2], [4, 3]],
 [[0, 1, 4], [3, 2]],
 [[1, 3, 4], [2, 0]],
 [[3, 1, 2], [0, 4]],
 [[4, 2, 1], [0, 3]],
 [[2, 3, 4], [0, 1]],
 [[0, 4, 2], [3, 1]],
 [[1, 4, 2], [0, 3]],
 [[4, 2, 1], [3, 0]],
 [[0, 2, 4], [1, 3]],
 [[2, 0, 4], [3, 1]],
 [[0, 2, 3], [4, 1]],
 [[0, 4, 2], [1, 3]],
 [[4, 2, 1], [0, 3]],
 [[2, 1, 0], [3, 4]],
 [[2, 0, 1], [3, 4]],
 [[1, 2, 0], [4, 3]],
 [[1, 3, 0], [2, 4]],
 [[3, 1, 4], [2, 0]],
 [[1, 4, 2], [3, 0]],
 [[1, 3, 4], [0, 2]],
 [[3, 1, 4], [2, 0]],
 [[4, 3, 2], [0, 1]],
 [[2, 4, 0], [1, 3]],
 [[3, 0, 1], [2, 4]],
 [[1, 3, 4], [0, 2]],
 [[4, 1, 3], [0, 2]],
 [[1, 3, 4], [0, 2]],
 [[3, 2, 0], [4, 1]],
 [[2, 1, 4], [3, 0]],
 [[4, 2, 0], [1, 3]],
 [[1, 0, 3], [2, 4]],
 [[1, 4, 2], [0, 3]],
 [[0, 4, 3], [1, 2]],
 [[3, 2, 0], [1, 4]],
 [[0, 2, 1], [4, 3]],
 [[4, 0, 1

In [4]:
ndp_solution = ndp_customers_by_cars[0]
ndp_solution

[[1, 4, 2], [0, 3]]

In [5]:
hdp_solution = hdp_customers_by_cars[0]
hdp_solution

[[7, 3, 4, 9, 6], [5, 8, 0, 1, 2]]

In [6]:
def find_edges(solution):
    edges = []
    for car in solution:
        if len(car) > 1:
            for i in range(len(car) - 1):
                edge = [car[i], car[i + 1]]
                edges.append(edge)
    return edges

In [7]:
edges = find_edges(solution=ndp_solution)
edges

[[1, 4], [4, 2], [0, 3]]

In [8]:
edge = edges[0]
edge

[1, 4]

In [9]:
def find_customer(solution, customer):
    for i in range(len(solution)):
        car = solution[i]
        if customer in car:
            return i, car.index(customer)
    raise ValueError("Customer not found.")


print(hdp_solution, find_customer(hdp_solution, 7))

[[7, 3, 4, 9, 6], [5, 8, 0, 1, 2]] (0, 0)


In [20]:
def find_customer_after_first_in_hdp_solution(
    hdp_solution, edge, force_same_car=FORCE_SAME_CAR
):
    first_customer_car_index, first_customer_position_index = find_customer(
        solution=hdp_solution, customer=edge[0]
    )
    # Normal: in the same car
    if len(hdp_solution[first_customer_car_index]) > first_customer_position_index + 1:
        return first_customer_car_index, first_customer_position_index + 1
    # If in the next car, get next position as usual
    elif not force_same_car:
        # get the first of next car
        if len(hdp_solution) > first_customer_car_index + 1:
            return first_customer_car_index + 1, 0
        # If in the last car already, get the first car
        else:
            return 0, 0
    else:
        return None, None


print(
    hdp_solution,
    [6, 5],
    find_customer_after_first_in_hdp_solution(hdp_solution, [6, 5], False),
)

[[7, 3, 4, 9, 6], [5, 8, 0, 1, 2]] [6, 5] (1, 0)


In [32]:
import copy


def local_search_single_edge(hdp_solution, edge, force_same_car=FORCE_SAME_CAR):
    hdp_solution = copy.deepcopy(hdp_solution)
    first_customer = edge[0]
    second_customer = edge[1]
    customer_after_first_car_index, customer_after_first_customer_index = (
        find_customer_after_first_in_hdp_solution(
            hdp_solution=hdp_solution, edge=edge, force_same_car=force_same_car
        )
    )

    if (
        customer_after_first_car_index is not None
        and customer_after_first_customer_index is not None
    ):
        customer_after_first = hdp_solution[customer_after_first_car_index][
            customer_after_first_customer_index
        ]
        second_customer_car_index, second_customer_position_index = find_customer(
            solution=hdp_solution, customer=second_customer
        )
        hdp_solution[customer_after_first_car_index][
            customer_after_first_customer_index
        ] = second_customer
        hdp_solution[second_customer_car_index][second_customer_position_index] = (
            customer_after_first
        )

    return hdp_solution


In [37]:
ndp_solution, hdp_solution = [
    customers_by_cars[0]
    for customers_by_cars in [ndp_customers_by_cars, hdp_customers_by_cars]
]
ndp_solution

[[1, 4, 2], [0, 3]]

In [38]:
hdp_solution

[[7, 3, 4, 9, 6], [5, 8, 0, 1, 2]]

In [40]:
edges = find_edges(ndp_solution)
edges

[[1, 4], [4, 2], [0, 3]]

In [44]:
def local_search(ndp_solution, hdp_solution, force_same_car=FORCE_SAME_CAR):
    edges = find_edges(ndp_solution)
    for edge in edges:
        hdp_solution = local_search_single_edge(
            hdp_solution=hdp_solution, edge=edge, force_same_car=force_same_car
        )
    return hdp_solution


hdp_solution_local_searched = local_search(
    ndp_solution=ndp_solution, hdp_solution=hdp_solution, force_same_car=True
)
print(hdp_solution)
print(ndp_solution)
print(hdp_solution_local_searched)

[[7, 3, 4, 9, 6], [5, 8, 0, 1, 2]]
[[1, 4, 2], [0, 3]]
[[7, 1, 2, 9, 6], [5, 8, 0, 3, 4]]


In [45]:
hdp_customers_by_cars_local_searched = [
    local_search(
        ndp_solution=ndp_solution,
        hdp_solution=hdp_solution,
        force_same_car=FORCE_SAME_CAR,
    )
    for ndp_solution, hdp_solution in zip(ndp_customers_by_cars, hdp_customers_by_cars)
]

In [46]:
for pre_ls, ndp, post_ls in zip(
    hdp_customers_by_cars, ndp_customers_by_cars, hdp_customers_by_cars_local_searched
):
    print(pre_ls)
    print(ndp)
    print(post_ls)

[[7, 3, 4, 9, 6], [5, 8, 0, 1, 2]]
[[1, 4, 2], [0, 3]]
[[2, 1, 7, 9, 6], [5, 8, 0, 3, 4]]
[[8, 0, 3, 4, 7], [2, 9, 6, 5, 1]]
[[3, 1, 2], [0, 4]]
[[8, 0, 4, 1, 2], [7, 9, 6, 5, 3]]
[[9, 3, 6, 1, 4], [5, 2, 8, 0, 7]]
[[1, 0, 3], [4, 2]]
[[9, 5, 6, 1, 0], [3, 7, 8, 4, 2]]
[[5, 6, 7, 9, 8], [3, 4, 0, 1, 2]]
[[0, 1, 2], [3, 4]]
[[5, 6, 7, 9, 8], [3, 4, 0, 1, 2]]
[[1, 8, 4, 2, 9], [6, 5, 7, 0, 3]]
[[0, 2, 3], [1, 4]]
[[3, 8, 9, 1, 4], [6, 5, 7, 0, 2]]
[[4, 3, 8, 0, 2], [5, 6, 7, 9, 1]]
[[4, 2, 0], [3, 1]]
[[4, 2, 0, 8, 3], [1, 6, 7, 9, 5]]
[[8, 4, 7, 6, 2], [1, 3, 0, 9, 5]]
[[2, 0, 4], [1, 3]]
[[8, 9, 7, 6, 2], [0, 4, 1, 3, 5]]
[[5, 0, 1, 2, 8], [6, 9, 3, 4, 7]]
[[1, 2, 4], [0, 3]]
[[5, 0, 3, 2, 4], [6, 9, 1, 8, 7]]
[[0, 8, 5, 7, 1], [4, 9, 6, 2, 3]]
[[0, 3, 1], [4, 2]]
[[0, 3, 1, 7, 5], [4, 2, 6, 9, 8]]
[[8, 4, 5, 1, 3], [9, 6, 7, 0, 2]]
[[0, 1, 2], [4, 3]]
[[2, 4, 3, 8, 5], [9, 6, 7, 0, 1]]
[[2, 1, 8, 7, 3], [0, 6, 5, 9, 4]]
[[0, 1, 4], [3, 2]]
[[0, 6, 8, 7, 3], [2, 1, 4, 9, 5]]
[[7, 2, 4,